name: CI pipeline



on:
  push:
    barnches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

  steps:
    - name:Checkout code
      uses:actions/checkout@5

    - name:set up node.js
      used:actions/setup-node@v3
      with:
        node-version:16
      

    - name:  install dependencies
      run: npm install

    - name: run test
      run: npm test
      
